version: '3'
services:
  
  api:
    image: "marla/api"
    ports:
      - "8080:8080"
    environment:
      - MARLA_REDIS_HOST=redis
    links:
      - redis

  worker:
    image: "marla/worker"
    environment:
      - REDIS_HOST=redis
    links:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"