version: '3'
services:
  
  api:
    image: openjdk:8
    working_dir: /opt/app
    command: ./gradlew bootRun
    volumes:
      - ./api:/opt/app 
    ports:
     - "8080:8080"
  
  redis:
    image: "redis:alpine"