redis:
  host: ${MARLA_REDIS_HOST}
  portValue: 6379

queue:
  waitQueue: marla:waitQueue
  resultsQueue: marla:resultsQueue

ssh:
  username: ${MARLA_SSH_USERNAME}
  password: ${MARLA_SSH_PASSWORD}
  host: ${MARLA_SSH_HOST}

eth:
  address: ${MARLA_ETH_ADDRESS}
  passphrase: ${MARLA_ETH_PASSPHRASE}
  ipcPath: ${MARLA_ETH_IPCPATH}

logging:
  level:
    com.marla.worker: DEBUG

server:
  port: 8090