apiVersion: v1
kind: Service
metadata:
  labels:
    com.marla.service: api
  name: api
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    com.marla.service: api
  type: NodePort
status:
  loadBalancer: {}
