apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    com.marla.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        com.marla.service: api
    spec:
      containers:
      - env:
        - name: MARLA_REDIS_HOST
          value: redis
        image: repo.treescale.com/ziggy42/marla/api:0.0.1
        name: api
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: private-repo-secret
status: {}
