apiVersion: v1
kind: Service
metadata:
  labels:
    com.marla.service: redis
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    com.marla.service: redis
  type: NodePort
status:
  loadBalancer: {}
