apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    com.marla.service: worker
  name: worker
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      labels:
        com.marla.service: worker
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis
        image: repo.treescale.com/ziggy42/marla/worker:0.0.3
        name: worker
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: private-repo-secret
status: {}
