apiVersion: v1
kind: Service
metadata:
  labels:
    com.marla.service: worker
  name: worker
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    com.marla.service: worker
status:
  loadBalancer: {}
